<!--Homepage-->
<div class="jumbotron">
    <h1>Home of Binge-Watch YouTubers</h1>
    <!--Form to submit to the index controller's start action-->
    <form action="<?php echo $this->url('application'); ?>/index/start" method="post">
        <!--Div with instructions-->
        <div style="text-align: center; margin-top:45px;">Enter URL of YouTube Video to Start With:</div>
        <!--Div with input group-->
        <div class="input-group" style="margin-top: 15px; margin-left: 20%; margin-right: 20%">
            <!--YouTube URL prompt add on to the left of the input box-->
            <span class="input-group-addon" id="basic-addon3">https://www.youtube.com/watch?v=</span>
            <input type="text" class="form-control" name="firstVideoURL" id="basic-url" aria-describedby="basic-addon3">
            <!--Start button add on to the right of the input box-->
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Start!</button>
            </span>
        </div>
    </form>
</div>
