<div id="player"></div>

<script>
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    
    var videosString = '<?php echo $this->videosString; ?>';
    var videosArray  = videosString.split(' ');
    var videosIndex  = 0;

    var player;
    function onYouTubeIframeAPIReady() {
        createPlayer();
    }
    
    function createPlayer() {
        player = new YT.Player('player', {
                                            height: '390',
                                            width:  '640',
                                            videoId: videosArray[videosIndex],
                                            events: {
                                                        'onReady': onPlayerReady,
                                                        'onStateChange': onPlayerStateChange
                                                    }
                                          });
    }

    function onPlayerReady(event) {
        event.target.playVideo();
    }

    function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.ENDED) {
            player.destroy();
            videosIndex++;
            if (videosIndex < videosArray.length) {
                createPlayer();
            }
        }
    }
</script>
